name: Changeset
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
jobs:
  changeset:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Label
        run: echo ${{ toJson((github.event) }}
